export const calloutCss: string;
export const containerCss: string;
export const filtersCss: string;
export const leftCss: string;
export const listHeaderGroupCss: string;
export const listInfoCss: string;
export const pageHeaderCss: string;
export const rightCss: string;
export const showMoreCss: string;
