export enum SchemaNames {
  AuthorsJson = "AuthorsJson",
  MarkdownRemark = "MarkdownRemark",
  MostReadAuthor = "MostReadAuthor",
  ReviewedWorksJson = "ReviewedWorksJson",
  TimelineEntry = "TimelineEntry",
  WorkAuthor = "WorkAuthor",
  ReadingProgressAuthor = "ReadingProgressAuthor",
  ReadingProgressJson = "ReadingProgressJson",
  UnreviewedWorksJson = "UnreviewedWorksJson",
  AuthorWork = "AuthorWork",
  ReviewedWorkReadingTimelineEntry = "ReviewedWorkReadingTimelineEntry",
  ReviewedWorkReading = "ReviewedWorkReading",
  MarkdownRemarkFrontmatter = "MarkdownRemarkFrontmatter",
}
