export enum SchemaNames {
  AuthorsJson = "AuthorsJson",
  MarkdownRemark = "MarkdownRemark",
  MostReadAuthor = "MostReadAuthor",
  ProgressJson = "ProgressJson",
  ReadingsJson = "ReadingsJson",
  ReadingWithReview = "ReadingWithReview",
  ReviewedWorksJson = "ReviewedWorksJson",
  TimelineEntry = "TimelineEntry",
  WorkAuthor = "WorkAuthor",
  WorksJson = "WorksJson",
  ReadingProgressAuthor = "ReadingProgressAuthor",
  ReadingProgressJson = "ReadingProgressJson",
  UnreviewedWorksJson = "UnreviewedWorksJson",
}
