export enum SchemaNames {
  AuthorsJson = "AuthorsJson",
  AuthorsJsonWork = "AuthorsJsonWork",
  AuthorsJsonWorkAuthor = "AuthorsJsonWorkAuthor",
  MarkdownRemark = "MarkdownRemark",
  ReadingStatsJson = "ReadingStatsJson",
  ReadingStatsJsonDistribution = "ReadingStatsJsonDistribution",
  ReadingStatsJsonMostReadAuthor = "ReadingStatsJsonMostReadAuthor",
  ReadingStatsJsonMostReadAuthorReading = "ReadingStatsJsonMostReadAuthorReading",
  ReviewedWorksJson = "ReviewedWorksJson",
  ReviewedWorksJsonIncludedWork = "ReviewedWorksJsonIncludedWork",
  ReviewedWorksJsonIncludedWorkAuthor = "ReviewedWorksJsonIncludedWorkAuthor",
  ReviewedWorksJsonMoreByAuthor = "ReviewedWorksJsonMoreByAuthor",
  ReviewedWorksJsonMoreWork = "ReviewedWorksJsonMoreWork",
  ReviewedWorksJsonMoreWorkAuthor = "ReviewedWorksJsonMoreWorkAuthor",
  ReviewedWorksJsonReading = "ReviewedWorksJsonReading",
  ReviewedWorksJsonReadingTimelineEntry = "ReviewedWorksJsonReadingTimelineEntry",
  ReviewedWorksJsonWorkAuthor = "ReviewedWorksJsonWorkAuthor",
  TimelineEntriesJson = "TimelineEntriesJson",
  TimelineEntriesJsonAuthor = "TimelineEntriesJsonAuthor",
  UnreviewedWorksJson = "UnreviewedWorksJson",
  UnreviewedWorksJsonWorkAuthor = "UnreviewedWorksJsonWorkAuthor",
}
